# openapi2-appengine.yaml
swagger: '2.0'
info:
  title: testing
  description: Sample API on API Gateway with an App Engine backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /getUser:
    get:
      summary: Greet a user
      operationId: getUser
      x-google-backend:
        address: "https://ca-lab.uc.r.appspot.com/"
        jwt_audience: "5001*****-dirb7r5k9o49hq33ri1midsmd7hk7d4l.apps.googleusercontent.com"
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      security:
      - google_id_token: []
 
securityDefinitions:
  google_id_token:
    authorizationUrl: ''
    flow: implicit
    type: oauth2
    x-google-issuer: "accounts.google.com"
    x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
